# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2016, '2016/2017'), (2017, '2017/2018'), (2018, '2018/2019'), (2019, '2019/2020'), (2020, '2020/2021')], unique=True)),
                ('inicioMatricula', models.DateField(verbose_name='Inicio matriculacion')),
                ('finMatricula', models.DateField(verbose_name='Fin matriculacion')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Curso')),
            ],
        ),
    ]
