# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20161231_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='year',
            field=models.IntegerField(choices=[(2012, '2012/2013'), (2013, '2013/2014'), (2014, '2014/2015'), (2015, '2015/2016'), (2016, '2016/2017'), (2017, '2017/2018'), (2018, '2018/2019'), (2019, '2019/2020'), (2020, '2020/2021'), (2021, '2021/2022')], unique=True),
        ),
    ]
